### PR TITLE
Add background model notebook and env file

### PR DESCRIPTION
**Pull request by adonath**
This PR adds the background model notebooks from the Gammapy tutorials.

### CODE REVIEW

**Comment by adonath** [comment]
@Bultako Do we specify a new environment name for each of the recipes? Or maybe pointing to an existing environment is sufficient?

**Comment by Bultako** [comment]
@adonath 

 - whatever name you chose for the env it will always be new environment for the CI, but it is true that it would be good to have different env names for each recipe so users could download several recipes with different envs.
- related to using dev version in the recipes, I'm not a big fan of this. It has to be specified somehow in the env dependencies with a different syntax for advanced users (pip+git), the dev version is not a snapshot of the codebase in the sense it is a release so we would have to specify a specific commit hash, etc..

**Comment by adonath** [comment]
Thanks @Bultako! 
> but it is true that it would be good to have different env names for each recipe so users could download several recipes with different envs.

Or even the other case: there might be recipes that don't require any special environment at all and there is maybe one default environment we provide...not saying it's a good idea, but just a thought I had.

> related to using dev version in the recipes, I'm not a big fan of this. It has to be specified somehow in the env dependencies with a different syntax for advanced users (pip+git), the dev version is not a snapshot of the codebase in the sense it is a release so we would have to specify a specific commit hash, etc.

This argument I totally see, however the consequence might be in some cases (as we have now already...) that the PRs remain open until the next release. However I could add an older version of the notebook that works with v0.18.2, but the maintenance work to adapt has already been done...

**Comment by Bultako** [comment]
We could also state in the [docs](https://gammapy.github.io/gammapy-recipes/_build/html/contributing.html) that providing a specific env name in the yaml file would allow users to execute the recipe in a clean environment, and avoid potential clashes with other envs that they could have created previously for other recipes.

As for using a specific dev version, advanced users could always tweak the env file, add `pip` to the env dependencies and declare the dev version of gammapy as a `git+https` pip dependency with a commit hash..

**Comment by Bultako** [comment]
@adonath Now, this link between a recipe and its environment is done in a very seamless way: the env file is placed in the recipe's folder. I think adding an extra layer to link the recipe to a separate `env.yaml` file stored somewhere complicates things, at least from the devel-app side.. Maybe there might be an in-between option, in the [steps proposed](https://gammapy.github.io/gammapy-recipes/_build/html/contributing.html) we could slightly modify the two first ones and say:

1. make a folder for your recipe 
2. copy in your recipe's folder the standard env file that we provide (or choose among the env files that we provide?)
3. modify the env file if needed

**Pull request merged**
