### PR TITLE
Interactive model editing recipe

### PR DESCRIPTION
**Pull request by facero**
metadata in the last cell where a png is displayed. Let's see if this works

### CODE REVIEW

**Comment by adonath** [comment]
@Bultako Is it possible to activate the notebook review app here as well? Might be helpful...

**Comment by facero** [comment]
CI has failed and I don't really understand why ...

**Comment by Bultako** [comment]
@facero

It seems there are conflicts among package versions and dependencies found when building the environment with `conda`. I've tried to build the env locally with `conda env create -f env.yml` ant this is what I get:

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
astropy=4.0 -> numpy[version='>=1.16'] -> python[version='2.7.*|3.5.*|3.6.*|3.7.*|3.8.*|>=2.7,<2.8.0a0|3.9.*|>=3.6|>=3.5,<3.6.0a0|3.4.*']
ipywidgets=6.0 -> python[version='2.7.*|3.5.*|3.6.*']
astropy=4.0 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
pandas=1.1 -> python-dateutil[version='>=2.7.3'] -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3|3.8.*|3.7.*|3.9.*']
qgrid=1.3.1 -> ipywidgets[version='>=7.0.0'] -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|3.4.*|3.7.*|3.8.*|3.9.*']
jupyter=1.0 -> python[version='2.7.*|3.5.*|3.6.*|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']
gammapy=0.18.2 -> python[version='>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0']
pandas=1.1 -> python[version='>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0']
ipywidgets=6.0 -> ipykernel[version='>=4.5.1'] -> python[version='3.4.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.5|>=3.7']
gammapy=0.18.2 -> click[version='>=7.0'] -> python[version='2.7.*|3.5.*|3.6.*|3.8.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|3.4.*|3.9.*|3.7.*']
jupyter=1.0 -> ipykernel -> python[version='3.4.*|>=3.6|>=3.5|3.8.*|3.7.*|3.9.*']
python=3.7
qgrid=1.3.1 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']

Package pypy3.6 conflicts for:
qgrid=1.3.1 -> notebook[version='>=4.0.0'] -> pypy3.6[version='7.3.0.*|7.3.1.*|7.3.2.*|7.3.3.*|>=7.3.1|>=7.3.2|>=7.3.3']
jupyter=1.0 -> ipykernel -> pypy3.6[version='7.3.*|7.3.0.*|7.3.1.*|7.3.2.*|7.3.3.*|>=7.3.1|>=7.3.2']
pandas=1.1 -> pypy3.6[version='>=7.3.2']
gammapy=0.18.2 -> numpy[version='>=1.19.4,<2.0a0'] -> pypy3.6[version='7.3.0.*|7.3.1.*|7.3.2.*|7.3.3.*|>=7.3.1|>=7.3.2|>=7.3.3']
ipywidgets=6.0 -> ipykernel[version='>=4.5.1'] -> pypy3.6[version='7.3.0.*|7.3.1.*|7.3.2.*|7.3.3.*|>=7.3.1|>=7.3.2|>=7.3.3']
astropy=4.0 -> numpy[version='>=1.16'] -> pypy3.6[version='7.3.0.*|7.3.1.*|7.3.2.*|7.3.3.*|>=7.3.1|>=7.3.2|>=7.3.3']
jupyter=1.0 -> pypy3.6[version='>=7.3.3']
pandas=1.1 -> numpy[version='>=1.18.5,<2.0a0'] -> pypy3.6[version='7.3.*|7.3.0.*|7.3.1.*|7.3.2.*|7.3.3.*|>=7.3.1|>=7.3.3']

Package setuptools conflicts for:
ipywidgets=6.0 -> ipython[version='>=4.0.0'] -> setuptools[version='>=18.5']
python=3.7 -> pip -> setuptools
gammapy=0.18.2 -> setuptools
astropy=4.0 -> setuptools

Package ca-certificates conflicts for:
jupyter=1.0 -> python -> ca-certificates
python=3.7 -> openssl[version='>=1.1.1j,<1.1.2a'] -> ca-certificates
ipywidgets=6.0 -> python=2.7 -> ca-certificates

Package expat conflicts for:
jupyter=1.0 -> pypy3.6[version='>=7.3.3'] -> expat[version='>=2.2.9,<2.3.0a0']
pandas=1.1 -> pypy3.6[version='>=7.3.2'] -> expat[version='>=2.2.9,<2.3.0a0']
python=3.7 -> pypy3.7=7.3.3 -> expat[version='>=2.2.9,<2.3.0a0']

Package libopenblas conflicts for:
astropy=4.0 -> numpy[version='>=1.16'] -> libopenblas[version='>=0.3.3,<1.0a0']
pandas=1.1 -> numpy[version='>=1.18.5,<2.0a0'] -> libopenblas[version='>=0.3.3,<1.0a0']
gammapy=0.18.2 -> scipy[version='>=1.2'] -> libopenblas[version='>=0.3.3,<1.0a0']

Package six conflicts for:
pandas=1.1 -> python-dateutil[version='>=2.7.3'] -> six[version='>=1.5']
gammapy=0.18.2 -> regions[version='>=0.4'] -> six
ipywidgets=6.0 -> traitlets[version='>=4.3.1,<5.0.0'] -> six

Package numpy-base conflicts for:
pandas=1.1 -> numpy[version='>=1.18.5,<2.0a0'] -> numpy-base[version='1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.17.2.*|1.17.3.*|1.17.4.*|1.18.1.*|1.18.5.*|1.19.1|1.19.1|1.19.1|1.19.1|1.19.1|1.19.1|1.19.2|1.17.0|1.17.0',build='py37h8a80b8c_0|py36h8a80b8c_0|py37h6575580_0|py36h6575580_0|py27ha711998_0|py37h6575580_0|py27h6575580_0|py36h6575580_0|py27ha711998_1|py37h6575580_1|py36ha711998_1|py36h6575580_1|py36ha711998_0|py27ha711998_0|py36h6575580_0|py27h6575580_0|py36ha711998_1|py27h6575580_1|py37h6575580_1|py27ha711998_1|py37h6575580_0|py27h6575580_0|py37h6575580_0|py27h6575580_0|py37h6575580_0|py37h6575580_0|py38h6575580_0|py38ha711998_0|py27h6575580_0|py39h7ca7dfd_1|py38h68fea81_0|py37hcfb5961_0|py37h68fea81_0|py37hcfb5961_0|py38h68fea81_0|py37h68fea81_0|py39h3a452eb_0|py39hde55871_0|py36h68fea81_0|py38hcfb5961_0|py36hcfb5961_0|py38hcfb5961_0|py36hcfb5961_0|py36h68fea81_0|py39hd037223_1|py27ha711998_0|py36h6575580_0|py36ha711998_0|py37ha711998_0|py36h6575580_0|py27ha711998_0|py36ha711998_0|py37ha711998_0|py36h6575580_0|py36ha711998_0|py36h6575580_0|py27h6575580_0|py27ha711998_0|py37ha711998_0|py36ha711998_0|py36h6575580_0|py37ha711998_0|py27ha711998_0|py37h6575580_0|py36ha711998_0|py27h6575580_0|py37ha711998_0|py36h6575580_0|py27ha711998_0|py36ha711998_0|py36h6575580_1|py37ha711998_1|py37h6575580_0|py37ha711998_0|py27h6575580_1|py37ha711998_1|py36ha711998_0|py37ha711998_0|py27h6575580_0|py37ha711998_0|py36ha711998_0|py27ha711998_0|py27h8a80b8c_0']
astropy=4.0 -> numpy[version='>=1.16'] -> numpy-base[version='1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.17.2.*|1.17.3.*|1.17.4.*|1.18.1.*|1.18.5.*|1.19.1|1.19.1|1.19.1|1.19.1|1.19.1|1.19.1|1.19.2|1.17.0|1.17.0',build='py36h6575580_0|py37h6575580_0|py36ha711998_0|py27h6575580_0|py36h6575580_0|py27ha711998_1|py37h6575580_1|py27h6575580_1|py36h6575580_0|py37h6575580_0|py37h6575580_1|py37ha711998_1|py36h6575580_1|py27h6575580_0|py37h6575580_0|py36h6575580_0|py27ha711998_0|py27h6575580_0|py37h6575580_0|py37h6575580_0|py38h6575580_0|py38ha711998_0|py27h6575580_0|py39h7ca7dfd_1|py38h68fea81_0|py37hcfb5961_0|py37h68fea81_0|py37hcfb5961_0|py38h68fea81_0|py37h68fea81_0|py39h3a452eb_0|py39hde55871_0|py36h68fea81_0|py38hcfb5961_0|py36hcfb5961_0|py38hcfb5961_0|py36hcfb5961_0|py36h68fea81_0|py39hd037223_1|py27ha711998_0|py36h6575580_0|py36ha711998_0|py37ha711998_0|py36h6575580_0|py27ha711998_0|py36ha711998_0|py37ha711998_0|py36h6575580_0|py37h6575580_0|py27h6575580_0|py37ha711998_0|py36ha711998_0|py27h6575580_0|py37ha711998_0|py27ha711998_0|py36ha711998_0|py37h6575580_0|py37ha711998_0|py36h6575580_0|py27ha711998_0|py36ha711998_0|py27ha711998_1|py27h6575580_1|py36ha711998_1|py27h6575580_0|py37ha711998_0|py27ha711998_0|py36ha711998_0|py36h6575580_1|py37ha711998_1|py36ha711998_1|py37ha711998_0|py27ha711998_0|py36ha711998_0']

Package numpy conflicts for:
gammapy=0.18.2 -> astropy[version='>=3.2'] -> numpy[version='>=1.11.3,<2.0a0|>=1.13.3,<2.0a0|>=1.13|>=1.14|>=1.16.5,<2.0a0|>=1.16|>=1.17.5,<2.0a0|>=1.17|>=1.19.5,<2.0a0|>=1.19|>=1.17.0,<2.0a0|>=1.16.6,<2.0a0|>=1.17.4,<2.0a0|>=1.14.6,<2.0a0|>=1.18.5,<2.0a0|>=1.19.2,<2.0a0|>=1.18.1,<2.0a0|>=1.9.3,<2.0a0']
qgrid=1.3.1 -> pandas[version='>=0.17.0'] -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11|>=1.11.*|>=1.12.1,<2.0a0|>=1.14.6,<2.0a0|>=1.15.4,<2.0a0|>=1.16.5,<2.0a0|>=1.16.6,<2.0a0|>=1.19.5,<2.0a0|>=1.19.4,<2.0a0|>=1.18.5,<2.0a0|>=1.19.2,<2.0a0|>=1.18.4,<2.0a0|>=1.18.1,<2.0a0|>=1.9.3,<2.0a0|>=1.9.*|>=1.9|>=1.8|>=1.7|>=1.13.3,<2.0a0|>=1.11.3,<2.0a0|>=1.9.3,<1.10.0a0']
pandas=1.1 -> numpy[version='>=1.15.4,<2.0a0|>=1.16.5,<2.0a0|>=1.18.5,<2.0a0|>=1.19.4,<2.0a0|>=1.19.2,<2.0a0|>=1.16.6,<2.0a0']
gammapy=0.18.2 -> numpy[version='>=1.19.4,<2.0a0']
astropy=4.0 -> numpy[version='>=1.16.5,<2.0a0|>=1.16.6,<2.0a0|>=1.16|>=1.19.4,<2.0a0|>=1.17|>=1.17.4,<2.0a0']

Package ipywidgets conflicts for:
jupyter=1.0 -> ipywidgets
qgrid=1.3.1 -> ipywidgets[version='>=7.0.0']
ipywidgets=6.0

Package prompt_toolkit conflicts for:
jupyter=1.0 -> jupyter_console -> prompt_toolkit[version='<2.0.0,>=1.0.0|>=1.0.0,<2.0.0|>=2.0.0,<2.1.0|>=2.0.0,<3.1.0,!=3.0.0,!=3.0.1|>=1.0.0,<2']
ipywidgets=6.0 -> ipython[version='>=4.0.0'] -> prompt_toolkit[version='>=1.0.3,<2.0.0|>=1.0.4,<2.0.0|>=2.0.0|>=2.0.0,<3|>=2.0.0,<4|>=2.0.0,<4,!=3.0.0,!=3.0.1']

Package astropy conflicts for:
gammapy=0.18.2 -> astropy[version='>=3.2']
gammapy=0.18.2 -> regions[version='>=0.4'] -> astropy
astropy=4.0

Package tzdata conflicts for:
jupyter=1.0 -> python[version='>=3.9,<3.10.0a0'] -> tzdata
pandas=1.1 -> python[version='>=3.9,<3.10.0a0'] -> tzdata
qgrid=1.3.1 -> python[version='>=3.9,<3.10.0a0'] -> tzdata
gammapy=0.18.2 -> python[version='>=3.9,<3.10.0a0'] -> tzdata
astropy=4.0 -> python[version='>=3.9,<3.10.0a0'] -> tzdata

Package pandas conflicts for:
qgrid=1.3.1 -> pandas[version='>=0.17.0|>=0.18.0']
pandas=1.1

Package jupyterlab_widgets conflicts for:
jupyter=1.0 -> ipywidgets -> jupyterlab_widgets[version='>=1.0.0']
qgrid=1.3.1 -> ipywidgets[version='>=7.0.0'] -> jupyterlab_widgets[version='>=1.0.0']
```

**Comment by facero** [comment]
changed version requirement from `=` to `>=`
environment now works locally in my machine

**Comment by Bultako** [comment]
> @Bultako Is it possible to activate the notebook review app here as well? Might be helpful...

I've just activated it now, I guess it will be displayed in the next PR.
For this one we can goo here https://app.reviewnb.com/gammapy/gammapy-recipes/pull/3/

**Comment by Bultako** [comment]
Hi @facero 
When reviewing this PR I realize that CI should not have passed.
There is an error raised when executing the notebook ``'Models' object has no attribute 'to_parameters_table'`` 
https://github.com/gammapy/gammapy-recipes/runs/1970674225?check_suite_focus=true#step:6:54

I guess this method was not implemented in gammapy 0.18.2. If you can fix this with version 0.18.2 we could hopefully accept the PR. If not, I can tell you that it is not possible to declare a `dev` version for gammapy in the `env.yml`

From my side, I will try to fix the CI to get a fail when execution of notebooks fails..

**Comment by facero** [comment]
good point. 
The current script works indeed only with the dev version.
So I'll guess I'll wait for the next release before finishing this PR then.

**Comment by Bultako** [comment]
@facero 

Yes, if this notebook cannot avoid using `models.to_parameters_table()`, it will have to wait for next release of gammapy.

**Comment by adonath** [comment]
@facero Please update to rely on v0.19.

**Comment by adonath** [comment]
Thanks @facero!

**Comment by facero** [comment]
thanks @adonath  for following this issue. Did you manage to implement 0.19 without issues ?

**Pull request merged**
