### PR TITLE
Adapt recipes for LTS v1.0.2

### LINKED ISSUE #13: Update recipes to v1.0
Recipes are all designed with old versions of gammapy namely v0.18.2 or v0.19. 

Given the various API changes in the v1.0 LTS version, the recipes should be updated to v1.0 if they are to be usable with limited effort.

Also the specific environment used in a given recipe should be made more visible.

### PR DESCRIPTION
**Pull request by Astro-Kirsty**
I made adaptions to mcmc and the dark-matter notebooks to work for LTS v1.0.2

I also updated the env files.

Resolves #13 

Resolves https://github.com/gammapy/gammapy/issues/4351

### CODE REVIEW

**Comment by Astro-Kirsty** [comment]
I also wonder if it is worth still having the dark matter recipe because this information is now available in a tutorial
https://docs.gammapy.org/1.2/tutorials/api/astro_dark_matter.html

**Comment by registerrier** [comment]
Thanks @Astro-Kirsty !

Have you checked whether the notebooks run fine? I had noticed some time ago that the interactive edition was not running at all.

**Comment by registerrier** [comment]
To clean the notebooks (black and strip, you can use the scripts here: 
```
from utils import notebook_black, notebook_strip

notebook_black(path_to_notebook)
notebook_strip(path_to_notebook)
```

**Comment by Astro-Kirsty** [comment]
> Thanks @Astro-Kirsty !
> 
> Have you checked whether the notebooks run fine? I had noticed some time ago that the interactive edition was not running at all.

Yes it worked fine for me

**Review by bkhelifi — APPROVED** [review]
Thanks @Astro-Kirsty! It looks good for me, beyond the Régis's comments

**Comment by Astro-Kirsty** [comment]
@registerrier, I just had to adapt the version of jupyter-lab to ensure it works correctly. 
All is good now

**Review by registerrier — APPROVED** [review]
Thanks @Astro-Kirsty

**Pull request merged**
